## These functions calculate the value of the inverse of a given matrix
## and store the result 

## Creates a special matrix object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)
}


## This function employs the object generated by the makeCacheMatrix function
## The cacheSolve function calculates the inverse of the matrix and then stores
## the result. In the case the inverse of the matrix has already been calculated 
## the function just gives back the stored result

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data.")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinverse(inv)
    print ("hello")
    inv
}